max_width = 80
wrap_comments = true
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
group_imports = "StdExternalCrate"